version: 0.2
phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Entered the build phase ...
      - mvn clean install

artifacts:
  files:
    - target/springWebProj-0.0.1-SNAPSHOT.jar
    - appspec.yml
    - deploy/start_server
   
